import { EncounterDetailData, EncounterSummary } from "../types/encounter"

export const mockEncounterDetail: EncounterDetailData = {
  encounter: {
    id: "LK000456",
    encounterCode: "LK000456",
    patientId: "pat-mock-01",
    examDate: "16/09/2024 10:30",
    examType: "Khám tổng quát",
    physicianName: "BS. Trần Minh Đức",
    room: "Phòng 101",
    status: "COMPLETED",
    statusLabel: "Đã khám",
    primaryDiagnosis: "Viêm đường hô hấp trên",
  },
  patient: {
    id: "pat-mock-01",
    patientCode: "BN000123",
    fullName: "Nguyễn Văn Hùng",
    dateOfBirth: "1985-03-12",
    age: 39,
    gender: "MALE",
    genderLabel: "Nam",
    identificationNumber: "0123456789012",
    phoneNumber: "0909 123 456",
    email: "hung.nguyen@gmail.com",
    address: "Số 12 Liễu Giai, Ba Đình, Hà Nội",
  },
  clinicalRecord: {
    chiefComplaint: "Ho nhiều, sốt nhẹ 2 ngày nay, đau rát họng, mệt mỏi",
    onsetDuration: "Khởi phát 2 ngày trước sau khi đi mưa về, ho khan tăng dần từng cơn, nuốt đau nhẹ, sốt gai rét từng cơn",
    medicalHistory: "Không ghi nhận tiền sử dị ứng thuốc hay bệnh mãn tính tim mạch, hen phế quản. Đã tiêm đủ vắc xin phòng cúm",
    vitals: {
      heartRate: 78,
      bloodPressure: "120/80",
      temperature: 37.8,
      respiratoryRate: 18,
      weight: 68,
      height: 172,
      bmi: 23.0,
      bmiClassification: "Bình thường",
      spo2: 98,
    },
    clinicalFindings: {
      throat: "Niêm mạc họng sung huyết đỏ nhẹ, hai amidan hơi sưng nề, không thấy chấm mủ hay giả mạc",
      lungs: "Lồng ngực cân đối di động theo nhịp thở. Rì rào phế nang êm dịu 2 phế trường, không rale ẩm, không rale nổ",
      heart: "T1, T2 đều rõ, nhịp tim đều 78ck/p, không phát hiện tiếng tim bất thường",
      abdomen: "Bụng mềm, không chướng, không điểm đau khu trú, gan lách không sờ thấy",
      otherFindings: "Bệnh nhân tỉnh táo, tiếp xúc tốt, da niêm hồng hào, không phù, hạch ngoại biên không sưng đau",
    },
    clinicalNotes: "Bệnh nhân nam 39 tuổi, vào viện vì sốt nhẹ và ho rát họng ngày thứ 2. Khám họng đỏ sung huyết, không mủ, phế trường sáng không rale, X-quang ngực chưa thấy tổn thương nhu mô phổi, công thức máu bạch cầu không tăng đáng kể. Phù hợp chẩn đoán nhiễm khuẩn đường hô hấp trên cấp.",
  },
  diagnoses: [
    {
      id: "diag-01",
      stt: 1,
      type: "PRIMARY",
      typeLabel: "Chẩn đoán chính",
      icdCode: "J06.9",
      diseaseName: "Nhiễm khuẩn hô hấp cấp tính trên, không xác định (Viêm đường hô hấp trên)",
      clinicalNotes: "Khởi phát cấp tính ngày thứ 2, họng đỏ sưng nhẹ, sốt nhẹ, chưa có biến chứng",
    },
    {
      id: "diag-02",
      stt: 2,
      type: "SECONDARY",
      typeLabel: "Chẩn đoán kèm theo",
      icdCode: "R05",
      diseaseName: "Ho khan từng cơn",
      clinicalNotes: "Ho tăng về đêm và gần sáng, không có đờm",
    },
    {
      id: "diag-03",
      stt: 3,
      type: "DIFFERENTIAL",
      typeLabel: "Chẩn đoán phân biệt",
      icdCode: "J20.9",
      diseaseName: "Viêm phế quản cấp, không đặc hiệu",
      clinicalNotes: "Đã loại trừ qua thăm khám lâm sàng phổi sạch và X-quang ngực không tổn thương",
    },
  ],
  prescriptions: {
    prescriptionCode: "DT-2024-00456",
    prescribedAt: "16/09/2024 10:45",
    items: [
      {
        id: "rx-01",
        stt: 1,
        medicationName: "Paracetamol",
        strength: "500mg",
        dosage: "1 viên x 3 lần/ngày",
        route: "Uống",
        quantity: "15 viên",
        instructions: "Sau ăn",
      },
      {
        id: "rx-02",
        stt: 2,
        medicationName: "Amoxicillin",
        strength: "500mg",
        dosage: "1 viên x 3 lần/ngày",
        route: "Uống",
        quantity: "21 viên",
        instructions: "Sau ăn, đủ liều",
      },
      {
        id: "rx-03",
        stt: 3,
        medicationName: "Cetirizine",
        strength: "10mg",
        dosage: "1 viên x 1 lần/ngày",
        route: "Uống",
        quantity: "10 viên",
        instructions: "Buổi tối trước khi ngủ",
      },
    ],
    doctorNotes: "Uống nhiều nước, nghỉ ngơi. Tái khám sau 5 ngày hoặc khi có dấu hiệu bất thường (sốt cao, khó thở).",
  },
  labOrders: [
    {
      id: "lab-01",
      stt: 1,
      code: "XN-01",
      category: "LAB",
      serviceName: "Công thức máu (CBC)",
      performedAt: "16/09/2024 11:30",
      status: "COMPLETED",
      statusLabel: "Hoàn tất",
      summaryResult: "Bình thường",
      actionType: "detail",
      detailViewKey: "cbc",
    },
    {
      id: "lab-02",
      stt: 2,
      code: "XN-02",
      category: "LAB",
      serviceName: "Sinh hóa máu",
      performedAt: "16/09/2024 11:30",
      status: "COMPLETED",
      statusLabel: "Hoàn tất",
      summaryResult: "Glucose: 5.6 mmol/L\nChức năng gan, thận bình thường",
      actionType: "detail",
      detailViewKey: "biochem",
    },
    {
      id: "lab-03",
      stt: 3,
      code: "HA-03",
      category: "IMAGING",
      serviceName: "Siêu âm ổ bụng",
      performedAt: "16/09/2024 14:00",
      status: "COMPLETED",
      statusLabel: "Hoàn tất",
      summaryResult: "Hình ảnh gan, mật, tụy, lách chưa phát hiện bất thường",
      actionType: "pdf",
    },
    {
      id: "lab-04",
      stt: 4,
      code: "HA-04",
      category: "IMAGING",
      serviceName: "X-quang ngực thẳng",
      performedAt: "16/09/2024 14:00",
      status: "COMPLETED",
      statusLabel: "Hoàn tất",
      summaryResult: "Phổi trong, không thấy tổn thương dạng nốt hay thâm nhiễm",
      actionType: "detail",
      detailViewKey: "xray",
    },
    {
      id: "lab-05",
      stt: 5,
      code: "CN-05",
      category: "FUNCTIONAL",
      serviceName: "Điện tâm đồ (ECG)",
      performedAt: "16/09/2024 15:10",
      status: "COMPLETED",
      statusLabel: "Hoàn tất",
      summaryResult: "Nhịp xoang đều, tần số 72 lần/phút. Không thấy bất thường",
      actionType: "detail",
    },
    {
      id: "lab-06",
      stt: 6,
      code: "NS-06",
      category: "ENDOSCOPY",
      serviceName: "Nội soi dạ dày",
      performedAt: "16/09/2024 15:30",
      status: "COMPLETED",
      statusLabel: "Hoàn tất",
      summaryResult: "Viêm dạ dày nhẹ, chưa thấy loét",
      actionType: "detail",
    },
    {
      id: "lab-07",
      stt: 7,
      code: "XN-07",
      category: "LAB",
      serviceName: "Tổng phân tích nước tiểu",
      performedAt: "16/09/2024 11:30",
      status: "COMPLETED",
      statusLabel: "Hoàn tất",
      summaryResult: "Bình thường",
      actionType: "detail",
    },
  ],
  laboratoryReportCBC: {
    orderCode: "XN-20240916-01",
    serviceName: "Công thức máu toàn phần (CBC)",
    sampleCollector: "KTV. Lê Thị Thảo",
    sampledAt: "16/09/2024 10:45",
    resultReportedAt: "16/09/2024 11:30",
    orderingPhysician: "BS. Trần Minh Đức",
    approvingPhysician: "BS. CKI. Vũ Đình Trọng",
    statusLabel: "Hoàn tất",
    indicators: [
      {
        stt: 1,
        indicatorName: "Số lượng bạch cầu",
        shortCode: "WBC",
        value: "7.4",
        unit: "G/L",
        referenceRange: "4.0 - 10.0",
        evaluation: "NORMAL",
        evaluationLabel: "Bình thường",
      },
      {
        stt: 2,
        indicatorName: "Số lượng hồng cầu",
        shortCode: "RBC",
        value: "4.85",
        unit: "T/L",
        referenceRange: "4.2 - 5.8",
        evaluation: "NORMAL",
        evaluationLabel: "Bình thường",
      },
      {
        stt: 3,
        indicatorName: "Lượng huyết sắc tố",
        shortCode: "HGB",
        value: "148",
        unit: "g/L",
        referenceRange: "130 - 175",
        evaluation: "NORMAL",
        evaluationLabel: "Bình thường",
      },
      {
        stt: 4,
        indicatorName: "Dung tích hồng cầu",
        shortCode: "HCT",
        value: "44.2",
        unit: "%",
        referenceRange: "38.0 - 50.0",
        evaluation: "NORMAL",
        evaluationLabel: "Bình thường",
      },
      {
        stt: 5,
        indicatorName: "Thể tích trung bình hồng cầu",
        shortCode: "MCV",
        value: "91.1",
        unit: "fL",
        referenceRange: "80.0 - 97.0",
        evaluation: "NORMAL",
        evaluationLabel: "Bình thường",
      },
      {
        stt: 6,
        indicatorName: "Lượng HST trung bình hồng cầu",
        shortCode: "MCH",
        value: "30.5",
        unit: "pg",
        referenceRange: "27.0 - 32.0",
        evaluation: "NORMAL",
        evaluationLabel: "Bình thường",
      },
      {
        stt: 7,
        indicatorName: "Nồng độ HST trung bình hồng cầu",
        shortCode: "MCHC",
        value: "335",
        unit: "g/L",
        referenceRange: "320 - 360",
        evaluation: "NORMAL",
        evaluationLabel: "Bình thường",
      },
      {
        stt: 8,
        indicatorName: "Số lượng tiểu cầu",
        shortCode: "PLT",
        value: "245",
        unit: "G/L",
        referenceRange: "150 - 450",
        evaluation: "NORMAL",
        evaluationLabel: "Bình thường",
      },
      {
        stt: 9,
        indicatorName: "Tỷ lệ bạch cầu trung tính",
        shortCode: "NEUT%",
        value: "62.5",
        unit: "%",
        referenceRange: "45.0 - 75.0",
        evaluation: "NORMAL",
        evaluationLabel: "Bình thường",
      },
      {
        stt: 10,
        indicatorName: "Tỷ lệ bạch cầu lympho",
        shortCode: "LYM%",
        value: "28.4",
        unit: "%",
        referenceRange: "20.0 - 40.0",
        evaluation: "NORMAL",
        evaluationLabel: "Bình thường",
      },
    ],
    conclusion: "Các chỉ số huyết học ngoại vi nằm trong giới hạn bình thường. Không có biểu hiện nhiễm trùng cấp nặng hay thiếu máu.",
    notes: "Mẫu máu tĩnh mạch chống đông EDTA đạt chuẩn kỹ thuật.",
  },
  diagnosticReportXRay: {
    orderCode: "HA-20240916-04",
    serviceName: "Chụp X-quang ngực thẳng (PA)",
    technique: "Chụp X-quang ngực thẳng kỹ thuật số (DR)",
    performedAt: "16/09/2024 14:00",
    orderingPhysician: "BS. Trần Minh Đức",
    radiologist: "BS. CKI. Hoàng Văn Hùng",
    device: "Máy X-quang kỹ thuật số Shimadzu Radspeed Pro",
    imageUrl: "/images/xray-sample.png",
    descriptionPoints: [
      "Khung xương lồng ngực cân đối, các xương sườn không thấy hình ảnh gãy hay biến dạng bất thường.",
      "Vòm hoành 2 bên đều, góc sườn hoành 2 bên nhọn sáng rõ.",
      "Nhu mô 2 phổi sáng đều, không thấy nốt mờ bất thường, không thấy hình ảnh thâm nhiễm hay đông đặc nhu mô.",
      "Rốn phổi hai bên kích thước và đậm độ trong giới hạn bình thường.",
      "Bóng tim kích thước bình thường, chỉ số tim - lồng ngực < 0.5.",
      "Trung thất không giãn, khí quản nằm ở vị trí đường giữa cân đối.",
    ],
    conclusion: "Hiện tại chưa phát hiện bất thường trên phim X-quang ngực thẳng.",
    recommendation: "Theo dõi lâm sàng và điều trị nội trú / ngoại trú theo phác đồ của bác sĩ khám.",
  },
  documents: [
    {
      id: "doc-01",
      stt: 1,
      name: "Phiếu khám tổng quát - LK000456.pdf",
      type: "Phiếu khám",
      sizeFormat: "PDF (420 KB)",
      createdAt: "16/09/2024 10:45",
      createdBy: "BS. Trần Minh Đức",
    },
    {
      id: "doc-02",
      stt: 2,
      name: "Đơn thuốc - DT000456.pdf",
      type: "Đơn thuốc",
      sizeFormat: "PDF (215 KB)",
      createdAt: "16/09/2024 10:48",
      createdBy: "BS. Trần Minh Đức",
    },
    {
      id: "doc-03",
      stt: 3,
      name: "Phiếu kết quả CBC - XN00456.pdf",
      type: "Kết quả xét nghiệm",
      sizeFormat: "PDF (310 KB)",
      createdAt: "16/09/2024 11:35",
      createdBy: "KTV. Lê Thị Thảo",
    },
    {
      id: "doc-04",
      stt: 4,
      name: "Phim X-quang ngực thẳng - HA00456.dcm",
      type: "Chẩn đoán hình ảnh",
      sizeFormat: "DICOM (18.4 MB)",
      createdAt: "16/09/2024 14:15",
      createdBy: "KTV. Phạm Văn Nam",
    },
    {
      id: "doc-05",
      stt: 5,
      name: "Kết quả siêu âm ổ bụng - SA00456.pdf",
      type: "Siêu âm",
      sizeFormat: "PDF (560 KB)",
      createdAt: "16/09/2024 14:20",
      createdBy: "BS. Hoàng Văn Hùng",
    },
  ],
  treatmentSummary: {
    conclusion: "Viêm đường hô hấp trên cấp tính mức độ nhẹ, đáp ứng tốt với điều trị ngoại trú.",
    treatmentPlan: "Điều trị ngoại trú bằng thuốc hạ sốt, kháng sinh, kháng histamin; bù nước điện giải.",
    doctorAdvice: "Nghỉ ngơi, uống nhiều nước ấm, súc họng nước muối sinh lý 3-4 lần/ngày. Tránh tiếp xúc khói bụi và thức uống quá lạnh. Tái khám sau 5 ngày hoặc khám lại ngay nếu sốt cao > 39°C, khó thở, tức ngực.",
    followUpDate: "21/09/2024",
  },
}

export const mockPatientEncounters: EncounterSummary[] = [
  {
    id: "LK000456",
    encounterCode: "LK000456",
    patientId: "pat-mock-01",
    examDate: "16/09/2024 10:30",
    examType: "Khám tổng quát",
    physicianName: "BS. Trần Minh Đức",
    room: "Phòng 101",
    status: "COMPLETED",
    statusLabel: "Đã khám",
    primaryDiagnosis: "Viêm đường hô hấp trên",
  },
  {
    id: "LK000389",
    encounterCode: "LK000389",
    patientId: "pat-mock-01",
    examDate: "12/06/2024 14:20",
    examType: "Khám chuyên khoa",
    physicianName: "BS. Nguyễn Thị Lan",
    room: "Phòng 204",
    status: "COMPLETED",
    statusLabel: "Hoàn tất",
    primaryDiagnosis: "Viêm xoang cấp",
  },
  {
    id: "LK000321",
    encounterCode: "LK000321",
    patientId: "pat-mock-01",
    examDate: "20/02/2024 08:15",
    examType: "Khám tái khám",
    physicianName: "BS. Lê Văn Nam",
    room: "Phòng 102",
    status: "COMPLETED",
    statusLabel: "Hoàn tất",
    primaryDiagnosis: "Tăng huyết áp vô căn",
  },
  {
    id: "LK000278",
    encounterCode: "LK000278",
    patientId: "pat-mock-01",
    examDate: "05/12/2023 09:00",
    examType: "Khám cấp cứu",
    physicianName: "BS. Phạm Thị Mai",
    room: "Cấp cứu",
    status: "CANCELLED",
    statusLabel: "Đã hủy",
    primaryDiagnosis: "Theo dõi ngộ độc thực phẩm",
  },
  {
    id: "LK000210",
    encounterCode: "LK000210",
    patientId: "pat-mock-01",
    examDate: "18/08/2023 15:45",
    examType: "Khám tổng quát",
    physicianName: "BS. Nguyễn Thị Hoa",
    room: "Phòng 103",
    status: "COMPLETED",
    statusLabel: "Hoàn tất",
    primaryDiagnosis: "Rối loạn tiêu hóa",
  },
  {
    id: "LK000156",
    encounterCode: "LK000156",
    patientId: "pat-mock-01",
    examDate: "03/04/2023 10:10",
    examType: "Khám chuyên khoa",
    physicianName: "BS. Trần Minh Đức",
    room: "Phòng 101",
    status: "COMPLETED",
    statusLabel: "Hoàn tất",
    primaryDiagnosis: "Đau đầu vận mạch",
  },
  {
    id: "LK000091",
    encounterCode: "LK000091",
    patientId: "pat-mock-01",
    examDate: "12/01/2023 16:35",
    examType: "Khám tái khám",
    physicianName: "BS. Lê Văn Nam",
    room: "Phòng 102",
    status: "COMPLETED",
    statusLabel: "Hoàn tất",
    primaryDiagnosis: "Khám sức khỏe định kỳ",
  },
  {
    id: "LK000045",
    encounterCode: "LK000045",
    patientId: "pat-mock-01",
    examDate: "20/10/2022 09:20",
    examType: "Khám tổng quát",
    physicianName: "BS. Nguyễn Thị Lan",
    room: "Phòng 204",
    status: "COMPLETED",
    statusLabel: "Hoàn tất",
    primaryDiagnosis: "Viêm dạ dày cấp",
  },
  {
    id: "LK000021",
    encounterCode: "LK000021",
    patientId: "pat-mock-01",
    examDate: "15/06/2022 11:00",
    examType: "Khám chuyên khoa",
    physicianName: "BS. Trần Minh Đức",
    room: "Phòng 101",
    status: "COMPLETED",
    statusLabel: "Hoàn tất",
    primaryDiagnosis: "Dị ứng thời tiết",
  },
  {
    id: "LK000008",
    encounterCode: "LK000008",
    patientId: "pat-mock-01",
    examDate: "10/03/2022 14:15",
    examType: "Khám tổng quát",
    physicianName: "BS. Phạm Thị Mai",
    room: "Phòng 105",
    status: "COMPLETED",
    statusLabel: "Hoàn tất",
    primaryDiagnosis: "Viêm kết mạc mắt",
  },
]

export async function fetchEncounterDetail(
  patientId: string,
  encounterId: string
): Promise<EncounterDetailData> {
  await new Promise((resolve) => setTimeout(resolve, 60))
  // Always return mockEncounterDetail for LK000456 or default
  return {
    ...mockEncounterDetail,
    encounter: {
      ...mockEncounterDetail.encounter,
      id: encounterId,
      encounterCode: encounterId,
      patientId,
    },
  }
}

export async function fetchPatientEncounters(
  _patientId: string
): Promise<EncounterSummary[]> {
  void _patientId
  await new Promise((resolve) => setTimeout(resolve, 50))
  return mockPatientEncounters
}
