export const medicalTerms = {
  patient: "Patient",
  appointment: "Appointment",
  encounter: "Encounter",
  reception: "Reception",
  patientCheckIn: "Patient Check-in",
  physician: "Physician",
  practitioner: "Practitioner",
  organization: "Organization",
  clinicalService: "Clinical Service",
  serviceRequest: "Service Request",
  laboratory: "Laboratory",
  diagnosticImaging: "Diagnostic Imaging",
  functionalDiagnostics: "Functional Diagnostics",
  diagnosticReport: "Diagnostic Report",
  prescription: "Prescription",
  healthExamination: "Health Examination",
  periodicHealthExamination: "Periodic Health Examination",
  payment: "Payment",
  paymentReceipt: "Payment Receipt",
} as const
